codecov:
    notify:
        after_n_builds: 1
        wait_for_ci: yes

coverage:
    status:
        project:
            default:
                target: 80%
                threshold: 1%
        patch:
            default:
                target: 100%

comment:
    layout: "header, diff, files"
    behavior: default
    require_changes: no
